export const FONTS = {
  Black: "UrbanistBlack",
  BlackItalic: "UrbanistBlackItalic",
  Bold: "UrbanistBold",
  BoldItalic: "UrbanistBoldItalic",
  ExtraBold: "UrbanistExtraBold",
  ExtraBoldItalic: "UrbanistExtraBoldItalic",
  ExtraLight: "UrbanistExtraLight",
  ExtraLightItalic: "UrbanistExtraLightItalic",
  Italic: "UrbanistItalic",
  Light: "UrbanistLight",
  LightItalic: "UrbanistLightItalic",
  Medium: "UrbanistMedium",
  MediumItalic: "UrbanistMediumItalic",
  Regular: "UrbanistRegular",
  SemiBold: "UrbanistSemiBold",
  SemiBoldItalic: "UrbanistSemiBoldItalic",
  Thin: "UrbanistThin",
  ThinItalic: "UrbanistThinItalic",
};
